### ISSUE TITLE
How to correctly package ts-toolbelt as dependency

### ISSUE THREAD

**Issue by mesqueeb** [millsp/ts-toolbelt#128]
#### Describe your question
Hi, I'm using ts-toolbelt to produce the return types of some util functions of mine:
- [filter-anything](https://github.com/mesqueeb/filter-anything#typescript) uses your `O.Omit` and `O.Pick` types.
- [merge-anything](https://github.com/mesqueeb/merge-anything#typescript-support) uses your `O.Compact` type.

However, in some monorepo projects of mine, some packages inside the monorepo have those utils of mine as well as `ts-toolbelt` as a dependency.

Now, I'm seeing issues when building, when the version of `ts-toolbelt` for `filter-anything` / `merge-anything` is different from the version in the monorepo project.

I get errors like these:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/3253920/87369381-568f2780-c5bb-11ea-829d-531da30cf2be.png">

and there are many logs with a bunch of errors all related to `ts-toolbelt`.

**Going forward I still plan to use `ts-toolbelt` for return types of many more utils I will host on npm, so I'd love to understand the best ways of doing so.**

Do you have any advice for me or have time to try and get to the bottom of this? Let me know! ;)

#### Search tags, topics
#packaging #module #version #clashing

**Comment by millsp** [comment]
Hi there,

I don't think your issue is related to this package, but rather TypeScript. I personally don't use lerna, but it seems like you are managing two version of the ts-toolbelt at the same time?

Maybe you should try to set all the versions to a fixed one in your dependencies. Otherwise, I found this https://stackoverflow.com/questions/31322525/confusing-duplicate-identifier-typescript-error-message.

Hope this helps!
