### ISSUE TITLE
Object.Partial creates wrong type

### ISSUE THREAD

**Issue by iyegoroff** [millsp/ts-toolbelt#139]
#### Describe the bug

The type created by Object.Partial is weaker than expected

#### Reproduce the bug
```ts
type T = { x: { y: never; z: () => 1 } }
// No error
const err: Object.Partial<T, 'deep'> = { x: { z: () => 'test' } }
```

#### Expected behavior
tsc should produce an error:
```
(property) z?: (() => 1) | undefined
Type '() => string' is not assignable to type '() => 1'.
  Type 'string' is not assignable to type '1'.ts(2322)
```

#### Possible Solution
```ts
type DeepPartial<T> = T extends Record<string, unknown>
  ? Partial<{ [Key in keyof T]: DeepPartial<T[Key]> }>
  : T

// Error: ...  Type 'string' is not assignable to type '1'.ts(2322)
const ok: DeepPartial<T> = { x: { z: () => 'test' } }
```

**Comment by millsp** [comment]
Heya @iyegoroff, thanks for reporting this. It's fixed. It will be out in a few minutes. Thanks!

**Comment by iyegoroff** [comment]
Looks like it is broken again in v9.6.0

**Comment by hjkcai** [comment]
I have found another broken case:

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTgXzgMyhEcDkMAzgLQwQQA2ARgKaUz4CwAUKzAJ5i1wCCcAXkRYKALjgBXAHYBrKRADuU9Oy48AQoJQA6AAoBDWMH2UAPLwA0BACa1aYfAD5WrWwGNKhnm4hSi8fXFeVh8-eGpxTSF9FxYgA)

```ts
import { O } from 'ts-toolbelt'

type A = { foo: unknown }
type B = O.Partial<A, 'deep'>

declare const a: A
const b: B = a
```

The code above results the following error:

```
Type 'A' is not assignable to type 'OptionalDeep<A>'.
  Types of property 'foo' are incompatible.
    Type 'unknown' is not assignable to type 'OptionalDeep<unknown> | undefined'.
      Type 'unknown' is not assignable to type 'OptionalDeep<unknown>'.(2322)
```

Normally `unknown` can never be passed into `OptionalDeep` because of the constraint `T extends object`. However when `unknown` is a value type of an object, it bypassed the constraint, resulting incorrect type `OptionalDeep<unknown>`.

IMO `unknown` may need to have special treatment to avoid this pitfall.
