### ISSUE TITLE
Dark theme is too hard to read code.

### ISSUE THREAD

**Issue by nhrones** [millsp/ts-toolbelt#313]
#### Is your feature request related to a problem?
  The dark blue words are unreadable. I need to select all code to read it!

#### Describe the solution you'd like
Provide a light theme, or change the Dark-Blue color.

**Comment by lynndylanhurley** [comment]
Second this. The docs are literally unusable.

**Comment by lynndylanhurley** [comment]
I see that this has been closed but that the issue hasn't been addressed. Thank you for showing us how this project manages feedback from its users.

**Comment by emahuni** [comment]
I don't understand why there is a won't fix label for something similar to this in the past. The documentation is useless because of a simple issue, theme. Why not just stick it to a light theme and leave it like that if it's hard to fix the switching? I am sure the author doesn't even use this documentation, coz there is NOTHING to read comprehensibly.

**Comment by Ziggoto** [comment]
The issue was closed by the same user that opened, not by this tool's developers. Unfortunately, there are two other open issues about this same topic, and no one got an answer from the developers. Here are the links: #306 and #326
